//iz night.h



//------------------ S E U I L   T E N S I O N   B A T T E R I E -----------------------

/*
    Permet de choisir la tension de detection batterie en sortie de Zener 12V (diode D9)
    Exemple : LPCOMP_REFSEL_REFSEL_Ref2_8Vdd = 2/8 * 3.3V = 0.825V donc seuil à 12.825V
*/

//#define IZN_SEUIL_DETECTION_BATTERY   LPCOMP_REFSEL_REFSEL_Ref1_8Vdd
//#define IZN_SEUIL_DETECTION_BATTERY     LPCOMP_REFSEL_REFSEL_Ref2_8Vdd
#define IZN_SEUIL_DETECTION_BATTERY   LPCOMP_REFSEL_REFSEL_Ref3_8Vdd      //mesure : 13.1V detecté
//#define IZN_SEUIL_DETECTION_BATTERY   LPCOMP_REFSEL_REFSEL_Ref4_8Vdd
//#define IZN_SEUIL_DETECTION_BATTERY   LPCOMP_REFSEL_REFSEL_Ref5_8Vdd
//#define IZN_SEUIL_DETECTION_BATTERY   LPCOMP_REFSEL_REFSEL_Ref6_8Vdd
//#define IZN_SEUIL_DETECTION_BATTERY   LPCOMP_REFSEL_REFSEL_Ref7_8Vdd
//#define IZN_SEUIL_DETECTION_BATTERY   LPCOMP_REFSEL_REFSEL_Ref1_16Vdd 
//#define IZN_SEUIL_DETECTION_BATTERY   LPCOMP_REFSEL_REFSEL_Ref3_16Vdd 
//#define IZN_SEUIL_DETECTION_BATTERY   LPCOMP_REFSEL_REFSEL_Ref5_16Vdd 
//#define IZN_SEUIL_DETECTION_BATTERY   LPCOMP_REFSEL_REFSEL_Ref7_16Vdd 
//#define IZN_SEUIL_DETECTION_BATTERY   LPCOMP_REFSEL_REFSEL_Ref9_16Vdd 
//#define IZN_SEUIL_DETECTION_BATTERY   LPCOMP_REFSEL_REFSEL_Ref11_16Vdd 
//#define IZN_SEUIL_DETECTION_BATTERY   LPCOMP_REFSEL_REFSEL_Ref13_16Vdd 
//#define IZN_SEUIL_DETECTION_BATTERY   LPCOMP_REFSEL_REFSEL_Ref15_16Vdd 
//#define IZN_SEUIL_DETECTION_BATTERY   LPCOMP_REFSEL_REFSEL_Ref9_16Vdd 